name: Server Deployment

on:
  push:
    branches:
      - master
    paths:
      - server/**

jobs:
  deploy-web:
    runs-on: ubuntu-latest


    steps:
    - name: Connect to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd messager
          git pull origin master
          cd server
          sh docker-delete.sh
          sh docker-build.sh
          sh docker-run.sh
